### ISSUE TITLE
Example window crashes on Mac OS X

### ISSUE THREAD

**Issue by chuchana** [Shinmera/qtools-ui#4]
Executing
```
(ql:quickload 'qtools-ui)
(cl+qt:with-main-window (w (make-instance 'qui:panel-container))
  (qui:add-widget (make-instance 'qui:panel :title "An empty panel. :(") w)
  (qui:add-widget (make-instance 'qui:panel :title "A slider, whoa!"
                                            :center (make-instance 'qui:slider)) w))
```
in sbcl opens the window, but it crashes as soon as the window is brought to the foreground:

```
sbcl: warning: sbcl crashed, killed by SIGSEGV.
sbcl itself has not crashed, but for transparency,
it will now kill itself (without dumping core) with the same signal
```

ccl freezes directly, without the window appearing.

Mac OS 10.13.4
SBCL 1.4.7 in the terminal and from Portacle 1.0 and 1.1
CCL 1.11.1

**Comment by Shinmera** [comment]
This is a problem with SBCL on the latest Mac OS related to *all* graphical applications. It is not a Qtools specific bug. Please turn to Apple or SBCL for a fix.

The CCL behaviour is another thing, though.

**Comment by chuchana** [comment]
I had forgotten about it, but I think that this was discussed related to the Lisp Game Jam, and that the SBCL maintainers won't fix what Apple broke. I hope Apple will do something about it, but it being Apple, I won't get my hopes up, so I'll try with an older OS version.

I was wrong about CCL: it was specific to the Mac App Store version. Since it did not provide any information on why it froze, I reinstalled the command line version, and that one displays a working window; it looks a bit weird, though:

<img width="526" alt="qtools-ui-ccl-mac" src="https://user-images.githubusercontent.com/3253908/39930423-003f9b46-553b-11e8-9f84-9c238fa616cd.png">

**Comment by chuchana** [comment]
Anyway, that wasn't the issue, so I'll close this.

**Comment by Shinmera** [comment]
Yeeaah, the weirdness is probably just due to QUI not being tested for edge cases though.

Glad to hear CCL works -- I'm guessing the app store version doesn't work because Qtools needs to hijack the main loop, which it probably wants to use for its own GUI thingy.

**Comment by chuchana** [comment]
As you suggested, it works with SBCL on older versions of OS X.

At least on Mac OS X 10.11.6, you have to manually load the Homebrew version of OpenSSL, since the built-in version produces SSL errors`[1]` during the `download-binaries` stages of the `qt-libs` installation.

```
(ql:quickload 'cffi)
(cffi:load-foreign-library "/usr/local/Cellar/openssl/1.0.2o_1/lib/libcrypto.1.0.0.dylib")
(let ((*features* (cons :cl+ssl-foreign-libs-already-loaded
                        *features*)))
  (ql:quickload :qtools-ui))
```

Just leaving this here in case someone else found this issue stumbling over the same errors I did.

`[1]` SSL error queue:
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
