### ISSUE TITLE
Update copyright in LICENSE

### ISSUE THREAD

**Issue by phoe** [Shinmera/qtools-ui#6]
https://github.com/Shinmera/qtools-ui/blob/f16748c2c7a05fbc69003882f71190406f5651b2/LICENSE#L2

I guess Perl Foundation owns Qtools now.

**Comment by Shinmera** [comment]
uh, no. they own the license document though.

**Comment by phoe** [comment]
Wait. This copyright is about the license file and not the software it's distributed with? That's a new one for me.

**Comment by Shinmera** [comment]
The same appears in lots of other licenses. https://www.gnu.org/licenses/gpl-3.0.txt
